version: '3.8'

services:
  markov-bot:
    build: .
    container_name: markov-chain-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./markov_data.db:/app/markov_data.db
    ports:
      - "8080:8080"
    restart: unless-stopped
